In [2]:
import pandas as pd
import numpy as np

In [3]:
submit_1 = pd.read_csv("mean_gbc_lasagne_5-13-15.csv").values
submit_2 = pd.read_csv("mean_gbc_lasagne_max_sums_gbc_lasagne_5-10-15.csv").values
submit_3 = pd.read_csv('gbc_lasagne_weighed-to-lasagne_5-3-15_8pm.csv').values
submit_4 = pd.read_csv('gbc_lasagne_5-3-15.csv').values
submit_5 = pd.read_csv('gbc_keras_weighed_5-1-15_9pm.csv').values
submit_6 = pd.read_csv("lasagne_drop_5-3-15_12pm_210-^^^-epochs.csv").values

In [5]:
gbc_vals = pd.read_csv('gbc_700_min_split-leaf-10_5-17-15.csv').values[:,1:]
las_vals = pd.read_csv('lasagne_drop_5-3-15_12pm_210-^^^-epochs.csv').values[:,1:]

mean_gbc_las = np.mean([gbc_vals, las_vals], axis=0)

In [10]:
sample = pd.read_csv('data/sampleSubmission.csv')

preds = pd.DataFrame(mean_gbc_las, index=sample.id.values, columns=sample.columns[1:])
preds.to_csv('mean-gbc_las_5-17-15.csv', index_label='id')
print("done predicting!")

done predicting!


In [11]:
# gbc_vals = pd.read_csv('gbc_from_lasagne_10-12-15_1500-est.csv').values[:, 1:]
new_gbc = [ i / np.max(i) for i in gbc_vals ]

gbc_confused_weights = [0.44444444444444442,
 0.85875706214689262,
 0.66216216216216217,
 0.43478260869565216,
 0.96153846153846156,
 0.97122302158273377,
 0.70967741935483875,
 0.95454545454545459,
 0.93023255813953487]

new_gbc *= np.array(gbc_confused_weights)

In [12]:
new_gbc[0]

array([ 0.0014004 ,  0.22002898,  0.24884029,  0.43478261,  0.0005224 ,
        0.00726335,  0.00829155,  0.00525088,  0.0028979 ])

In [13]:
las_vals = pd.read_csv('lasagne_drop_5-3-15_12pm_210-^^^-epochs.csv').values[:, 1:]
new_las = [ i / np.max(i) for i in las_vals ]

lasagne_confused_weights = [0.33333333333333331,
 0.81142857142857139,
 0.52777777777777779,
 0.5714285714285714,
 0.96666666666666667,
 0.92307692307692313,
 0.53846153846153844,
 0.93023255813953487,
 0.86274509803921573]

new_las *= np.array(lasagne_confused_weights)

In [14]:
mean_weighted_matrix = np.mean([new_gbc, new_las], axis=0)
mean_weighted_matrix = [ i / np.max(i) for i in mean_weighted_matrix ]

In [15]:
sample = pd.read_csv('data/sampleSubmission.csv')

preds = pd.DataFrame(mean_weighted_matrix, index=sample.id.values, columns=sample.columns[1:])
preds.to_csv('mean-weighted_las_gbc_5-17-15_finalz.csv', index_label='id')
print("done predicting!")

done predicting!


In [31]:
mean_all = np.mean([submit_1, submit_2, submit_3, submit_4, submit_5, submit_6], axis=0)
mean_all = mean_all[:,1:]

1.000627140432786

In [3]:
keras_df = pd.read_csv("keras_750_20_bd.csv")
keras_df.head()

id   Class_1   Class_2       Class_3   Class_4       Class_5   Class_6  \
0   1  0.001208  0.414922  3.436776e-01  0.219289  1.524724e-04  0.000422   
1   2  0.004386  0.004092  1.318493e-03  0.000816  6.016449e-05  0.686232   
2   3  0.000001  0.000000  5.443987e-08  0.000001  2.195154e-10  0.999988   
3   4  0.000020  0.467517  5.304480e-01  0.001515  2.762650e-05  0.000022   
4   5  0.215202  0.000021  5.599423e-06  0.000009  4.300417e-06  0.001567   

    Class_7   Class_8   Class_9  
0  0.019751  0.000228  0.000351  
1  0.005540  0.294713  0.002842  
2  0.000000  0.000008  0.000003  
3  0.000093  0.000230  0.000127  
4  0.000055  0.016839  0.766297

In [4]:
gbc_df = pd.read_csv("gbc_from_lasagne_10-12-15_1500-est.csv")
gbc_df.head()

id   Class_1   Class_2   Class_3   Class_4   Class_5   Class_6   Class_7  \
0   1  0.000317  0.098941  0.329279  0.567213  0.000004  0.001196  0.001733   
1   2  0.003136  0.006055  0.004064  0.001255  0.000021  0.910094  0.002973   
2   3  0.000041  0.000123  0.000053  0.000023  0.000000  0.999556  0.000050   
3   4  0.000795  0.401646  0.588507  0.003408  0.000005  0.000762  0.000951   
4   5  0.076382  0.002801  0.002842  0.000585  0.000019  0.008879  0.003580   

    Class_8   Class_9  
0  0.000898  0.000419  
1  0.069942  0.002461  
2  0.000119  0.000035  
3  0.001267  0.002659  
4  0.086273  0.818641

In [28]:
# gbc_vals = gbc_df.drop("id", 1).values
# keras_vals = keras_df.drop("id", 1).values

# keras_vals.shape

In [5]:
lasagne_df = pd.read_csv("lasagne_drop_5-3-15_12pm_210-^^^-epochs.csv")
# lasagne_df = pd.read_csv("lasagne_drop_5-7-15_200-epochs_lookin-good.csv")
lasagne_df.head()

id       Class_1       Class_2       Class_3       Class_4       Class_5  \
0   1  5.472575e-05  3.430429e-01  3.861805e-01  2.670003e-01  2.015497e-09   
1   2  1.445872e-05  1.377777e-04  3.506232e-05  1.822014e-06  8.336285e-05   
2   3  2.667422e-10  1.487251e-09  3.535204e-10  3.749474e-10  3.447612e-10   
3   4  1.755881e-07  8.070088e-01  1.856771e-01  7.307001e-03  6.057481e-10   
4   5  1.151597e-01  2.189253e-09  2.426725e-11  1.649303e-12  2.046779e-12   

        Class_6       Class_7       Class_8   Class_9  
0  1.572285e-07  3.721051e-03  9.668805e-08  0.000000  
1  7.574223e-01  4.264549e-04  2.417141e-01  0.000165  
2  9.999863e-01  1.197206e-09  1.351929e-05  0.000000  
3  4.090087e-09  5.316110e-06  1.042623e-07  0.000001  
4  9.362987e-05  4.240328e-05  3.121469e-03  0.881583

In [6]:
np.sum(lasagne_df.iloc[100, 1:])

0.99999999999999978

In [8]:
gbc_vals = gbc_df.drop("id", 1).values
keras_vals = keras_df.drop("id", 1).values
lasagne_vals = lasagne_df.drop("id", 1).values

In [9]:
gbc_maxes = np.max(gbc_vals, axis=1)
lasagne_maxes = np.max(lasagne_vals, axis=1)
keras_maxes = np.max(keras_vals, axis=1)

gbc_maxes

array([ 0.56721323,  0.91009388,  0.99955561, ...,  0.60026974,
        0.48951264,  0.5448619 ])

In [27]:
lasagne_maxes

array([ 0.38618048,  0.75742233,  0.99998634, ...,  0.70039477,
        0.61508388,  0.49847414])

In [11]:
max_sums = gbc_vals[10,:]*gbc_maxes[10] + lasagne_vals[10,:]*lasagne_maxes[10]
max_sums

array([  3.62379212e-03,   4.50066595e-01,   3.36668597e-01,
         1.09240866e-01,   1.57678330e-04,   5.07941133e-03,
         7.02851588e-02,   2.37538818e-03,   1.96340744e-03])

In [14]:
max_sums = [ gbc_vals[i, :]*gbc_maxes[i] +  lasagne_vals[i,:]*lasagne_maxes[i] + \
            keras_vals[i, :] * keras_maxes[i] for i in range(len(gbc_vals))]

In [15]:
max_sums = np.array(max_sums)
max_sums.shape

(144368, 9)

In [14]:
np.sum(max_sums[0])

0.87978336658872081

In [16]:
sample = pd.read_csv('data/sampleSubmission.csv')

preds = pd.DataFrame(max_sums, index=sample.id.values, columns=sample.columns[1:])
preds.to_csv('combined-fed_gbc_lasagne_max_sums_5-13-15.csv', index_label='id')
print("done predicting!")

done predicting!


In [17]:
mean_array = np.mean([gbc_vals, keras_vals, lasagne_vals], axis=0)
mean_array.shape

(144368, 9)

In [6]:
mean_gbc_keras = np.mean([gbc_vals, keras_vals], axis=0)
mean_gbc_lasagne = np.mean([gbc_vals, lasagne_vals], axis=0)

In [18]:
sample = pd.read_csv('data/sampleSubmission.csv')

preds = pd.DataFrame(mean_array, index=sample.id.values, columns=sample.columns[1:])
preds.to_csv('mean_gbc_lasagne_5-13-15.csv', index_label='id')
print("done predicting!")

done predicting!


In [9]:
sample = pd.read_csv('data/sampleSubmission.csv')

preds = pd.DataFrame(mean_gbc_lasagne, index=sample.id.values, columns=sample.columns[1:])
preds.to_csv('gbc_lasagne_5-3-15.csv', index_label='id')
print("done predicting!")

done predicting!


In [8]:
a = 0.44
b = 0.42
c = 0.51

w_a = (1/a)/(1/a+1/b+1/c)
w_b = (1/b)/(1/a+1/b+1/c)
w_c = (1/c)/(1/a+1/b+1/c)

In [25]:
w_a+w_b

0.7035611164581328

In [6]:
w_b = 0.1
w_a = 0.9

In [9]:
# mean_weighted = gbc_vals*w_a + lasagne_vals*w_b + keras_vals*w_c

# mean_weight

In [18]:
print(mean_array)

NameError: name 'mean_array' is not defined

In [12]:
print(mean_weighted)

[[  5.34834835e-04   3.32735383e-01   3.16994469e-01 ...,   7.69339420e-03
    5.71986610e-04   3.11195516e-04]
 [  2.25432513e-03   3.72304073e-03   1.64313067e-03 ...,   3.18442670e-03
    2.75981697e-01   1.79103584e-03]
 [  1.65201995e-05   4.43558573e-05   2.21057489e-05 ...,   1.94718799e-05
    6.02223403e-05   1.68822104e-05]
 ..., 
 [  2.68304898e-04   6.37763681e-01   3.24422356e-01 ...,   4.89044867e-03
    6.76248645e-04   2.75968093e-04]
 [  2.52847437e-04   3.54699439e-01   4.83551460e-02 ...,   7.78154850e-04
    2.27994986e-04   1.65175975e-04]
 [  1.55424061e-04   4.69862240e-01   4.84007964e-01 ...,   2.34921916e-02
    2.43716943e-04   1.35136707e-04]]


In [14]:
sample = pd.read_csv('data/sampleSubmission.csv')

preds = pd.DataFrame(mean_weighted, index=sample.id.values, columns=sample.columns[1:])
preds.to_csv('gbc_lasagne_keras_weighed_5-8-15b.csv', index_label='id')
print("done predicting!")

done predicting!


In [37]:
print(mean_weighted.shape)
print(mean_weighted.max(axis=1).shape)

(144368, 9)
(144368,)


In [48]:
mean_max = [ i / np.max(i) for i in mean_weighted ]

In [54]:
mean_max_array = np.array(mean_max)

In [55]:
sample = pd.read_csv('data/sampleSubmission.csv')

preds = pd.DataFrame(mean_max_array, index=sample.id.values, columns=sample.columns[1:])
preds.to_csv('gbc_lasagne_keras_weighed_MAX_5-6-15b.csv', index_label='id')
print("done predicting!")

done predicting!


In [15]:
gbc_confused_weights = [0.44444444444444442,
 0.85875706214689262,
 0.66216216216216217,
 0.43478260869565216,
 0.96153846153846156,
 0.97122302158273377,
 0.70967741935483875,
 0.95454545454545459,
 0.93023255813953487]

In [16]:
lasagne_confused_weights = [0.80508035251425614,
 0.91787619402059295,
 0.63218390804597702,
 0.63545150501672243,
 0.99196787148594379,
 0.97573399363282631,
 0.86192321239873193,
 0.96951795841209831,
 0.94651866801210893]

In [17]:
gbc_confused_weights = [0.44444444444444442,
 0.85875706214689262,
 0.66216216216216217,
 0.43478260869565216,
 0.96153846153846156,
 0.97122302158273377,
 0.70967741935483875,
 0.95454545454545459,
 0.93023255813953487]

#  lasagne_confused_weights = [0.80508035251425614,
#  0.91787619402059295,
#  0.63218390804597702,
#  0.63545150501672243,
#  0.99196787148594379,
#  0.97573399363282631,
#  0.86192321239873193,
#  0.96951795841209831,
#  0.94651866801210893]

lasagne_confused_weights = [0.33333333333333331,
 0.81142857142857139,
 0.52777777777777779,
 0.5714285714285714,
 0.96666666666666667,
 0.92307692307692313,
 0.53846153846153844,
 0.93023255813953487,
 0.86274509803921573]

In [18]:
gbc_contribute = gbc_confused_weights / np.sum([gbc_confused_weights, lasagne_confused_weights], axis=0)
gbc_contribute

array([ 0.57142857,  0.51416863,  0.55646688,  0.43209877,  0.49867021,
        0.51270815,  0.56858847,  0.5064498 ,  0.51881994])

In [19]:
lasagne_contribute = lasagne_confused_weights / np.sum([gbc_confused_weights, lasagne_confused_weights], axis=0)
lasagne_contribute

array([ 0.42857143,  0.48583137,  0.44353312,  0.56790123,  0.50132979,
        0.48729185,  0.43141153,  0.4935502 ,  0.48118006])

In [20]:
gbc_lasagne_conf_coop_vals = (gbc_vals * gbc_contribute) + (lasagne_vals * lasagne_contribute)

In [26]:
np.sum(gbc_lasagne_conf_coop_vals[0])

0.97901464505051272

In [33]:
true_mean_array = np.mean([gbc_vals, lasagne_vals], axis=0)

In [34]:
sample = pd.read_csv('data/sampleSubmission.csv')

preds = pd.DataFrame(true_mean_array, index=sample.id.values, columns=sample.columns[1:])
preds.to_csv('gbc_lasagne_coop_true_mean_5-12-15.csv', index_label='id')
print("done predicting!")

done predicting!
